/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.49
 * Generated at: 2020-06-05 01:51:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class AddressBook_005f02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script>\n");
      out.write("\tfunction delete_Click() {\n");
      out.write("\t\tif (confirm(\"정말 삭제하시겠습니까??\") == true){    //확인\n");
      out.write("\t\t\tlocation.href=\"AddressDelete.jsp\";\n");
      out.write("\t\t }else{   //취소\n");
      out.write("\t\t     return false;\n");
      out.write("\t\t }\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원 정보 수정</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t");

		request.setCharacterEncoding("utf-8");
		int seq = Integer.parseInt(request.getParameter("seq"));
		session.setAttribute("SEQ", seq);
		String strName = null;
		String strTel = null;
		String strAddress = null;
		String strEmail = null;
		String strRelation = null;
		
		//Database 연결
		String url_mysql = "jdbc:mysql://localhost:3306/addressBook?serverTimezone=Asia/Seoul&characterEncoding=utf8&useSSL=false";
		  	String id_mysql = "root";
		String pw_mysql = "qwer1234";
		
		
		String WhereDefault = "select name, tel, address, email, relation from customerBook where seq = " + Integer.toString(seq);
		
		 try {
		    	Class.forName("com.mysql.cj.jdbc.Driver");
		    	Connection conn_mysql = DriverManager.getConnection(url_mysql, id_mysql, pw_mysql);
		    	Statement stmt_mysql = conn_mysql.createStatement();
		    	
		    	ResultSet rs = stmt_mysql.executeQuery(WhereDefault);
		    	
		    	while(rs.next()) {
		    		strName = rs.getString(1);
		    		strTel = rs.getString(2);
		    		strAddress = rs.getString(3);
		    		strEmail = rs.getString(4);
		    		strRelation = rs.getString(5);
		    		
		    	}
		    	
		    	conn_mysql.close();  //웹에서는 어차피 연결 끊기기 때문에 큰 의미 없다. 
		    	
		    }catch (Exception e) {
		    	e.printStackTrace();
		    }
	
	
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<h2 align=\"center\">");
      out.print(strName );
      out.write("님의 정보</h2>\n");
      out.write("\t<br><br>\n");
      out.write("\t<form action = \"AddressUpdate.jsp\" method=\"post\" align=\"center\">\n");
      out.write("\t<table style=\"border-collapse:collapse; border:2px gray solid;\" align=\"center\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"100\">이름</td>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"300\" align=\"left\"><input type=\"text\" name=\"name\" value=\"");
      out.print(strName );
      out.write("\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"100\">전화번호</td>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"300\" align=\"left\"><input type=\"text\" name=\"tel\" value=\"");
      out.print(strTel );
      out.write("\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"100\">주소</td>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"300\" align=\"left\"><input type=\"text\" name=\"address\" value=\"");
      out.print(strAddress );
      out.write("\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"100\">전자우편</td>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"300\" align=\"left\"><input type=\"text\" name=\"email\" value=\"");
      out.print(strEmail );
      out.write("\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"100\">관계</td>\n");
      out.write("\t\t\t\t<td style=\"border:1px gray solid;\" width=\"300\" align=\"left\"><input type=\"text\" name=\"relation\" value=\"");
      out.print(strRelation );
      out.write("\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t\n");
      out.write("\t<h3 align=\"center\">수정이 완료되면 확인을 눌러주세요!</h3>\n");
      out.write("\t<br>\n");
      out.write("\t\n");
      out.write("\t<br><input type=\"submit\" value=\"확인\" align=\"center\">\n");
      out.write("\t</form>\n");
      out.write("\t<form action=\"AddressBook_01.jsp\" method=\"post\" align=\"center\">\n");
      out.write("\t<input type=\"submit\" value=\"뒤로가기\">\n");
      out.write("\t</form> <br><br>\n");
      out.write("\t<input type=\"button\" value=\"삭제\" align=\"center\" onclick=\"delete_Click();\">\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
