/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.49
 * Generated at: 2020-06-19 09:17:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class prdCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script>\n");
      out.write("\t\tfunction clickFunc() {\n");
      out.write("\t\t\twindow.close();\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/* 미입력 알럿 */\n");
      out.write("\t\tfunction check() {\n");
      out.write("\t\t  if(revProduct.productImage.value == \"\") {\n");
      out.write("\t\t    alert(\"사진을 등록해 주세요.\");\n");
      out.write("\t\t    revProduct.productImage.focus();\n");
      out.write("\t\t    return false;\n");
      out.write("\t\t  }\n");
      out.write("\t\t  else if(revProduct.title.value == \"\") {\n");
      out.write("\t\t    alert(\"상품이름을 입력해 주세요.\");\n");
      out.write("\t\t    revProduct.title.focus();\n");
      out.write("\t\t    return false;\n");
      out.write("\t\t  } \n");
      out.write("\t\t  else if(revProduct.price.value == \"\") {\n");
      out.write("\t\t\t    alert(\"가격을 입력해 주세요.\");\n");
      out.write("\t\t\t    revProduct.price.focus();\n");
      out.write("\t\t\t    return false;\n");
      out.write("\t\t  } \n");
      out.write("\t\t  else if(revProduct.date1.value == \"\") {\n");
      out.write("\t\t\t    alert(\"대여 시작일을 입력해 주세요.\");\n");
      out.write("\t\t\t    revProduct.date1.focus();\n");
      out.write("\t\t\t    return false;\n");
      out.write("\t\t  } \n");
      out.write("\t\t  else if(revProduct.date2.value == \"\") {\n");
      out.write("\t\t\t    alert(\"대여 종료일을 입력해 주세요.\");\n");
      out.write("\t\t\t    revProduct.date2focus();\n");
      out.write("\t\t\t    return false;\n");
      out.write("\t\t} \n");
      out.write("\t\t  else if(revProduct.hash.value == \"\") {\n");
      out.write("\t\t\t    alert(\"상품을 홍보할 해시태그를 입력해 주세요.\");\n");
      out.write("\t\t\t    revProduct.hash.focus();\n");
      out.write("\t\t\t    return false;\n");
      out.write("\t\t} \n");
      out.write("\t\t  else if(revProduct.info.value == \"\") {\n");
      out.write("\t\t\t    alert(\"상품을 소개를 입력해 주세요.\");\n");
      out.write("\t\t\t    revProduct.info.focus();\n");
      out.write("\t\t\t    return false;\n");
      out.write("\t\t} \n");
      out.write("\t\t \n");
      out.write("\t\t  else return true;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("\t.prdCheck {\n");
      out.write("\t\tborder-radius: 8px;\n");
      out.write("\t\tborder: solid 2px Black;\n");
      out.write("\t\twidth: 200 px;\n");
      out.write("\t\theight: 720 px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>댓글 수정</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"prdCheck\" align=\"center\" >\n");
      out.write("\t\t\t<form action=\"prdRev.bill\" method=\"post\" align=\"center\"  name=\"revProduct\" onsubmit=\"return check()\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: right;\">사진 :</div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"file\" name=\"productImage\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: right;\">title :</div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" name=\"title\" id=\"title\" size=\"58\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: right;\">price : </div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"text\" name=\"price\" id=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> / 원</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: right;\">대여시작 :</div>\n");
      out.write("\t\t\t\t\t\t<div> <input type=\"date\" name=\"date1\" id=\"date1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.date1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: right;\">대여종료 :</div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"date\" name=\"date2\" id=\"date2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.date2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: right;\">해시태그 :</div>\n");
      out.write("\t\t\t\t\t\t<div> <textarea rows=\"2\" cols=\"50\" name=\"hash\" id=\"hash\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.hash }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: right;\">상품소개 :</div>\n");
      out.write("\t\t\t\t\t\t<div> <textarea rows=\"10\" cols=\"50\" name=\"info\" id=\"info\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.info }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div><input type=\"hidden\" name=\"prdseq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.prdseq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div><input type=\"submit\" value=\"수정\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t<div align=\"center\" style=\"margin-top : 20px;\"><button onclick=\"clickFunc();\">닫기</button></div> \n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
