/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.49
 * Generated at: 2020-06-22 06:05:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/usr/local/apache-tomcat-8.5.49/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("file:/usr/local/apache-tomcat-8.5.49/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1574016365000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("\tfunction myFunction() {\n");
      out.write("\t\t  document.getElementById(\"myDropdown\").classList.toggle(\"show\");\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\twindow.onclick = function(event) {\n");
      out.write("\t  if (!event.target.matches('.dropbtn')) {\n");
      out.write("\t    var dropdowns = document.getElementsByClassName(\"dropdown-content\");\n");
      out.write("\t    var i;\n");
      out.write("\t    for (i = 0; i < dropdowns.length; i++) {\n");
      out.write("\t      var openDropdown = dropdowns[i];\n");
      out.write("\t      if (openDropdown.classList.contains('show')) {\n");
      out.write("\t        openDropdown.classList.remove('show');\n");
      out.write("\t      }\n");
      out.write("\t    }\n");
      out.write("\t  }\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction borrowAct() {\n");
      out.write("\t\tvar gsWin = window.open(\"about:blank\", \"BORROW\",  'width=500, height=500');\n");
      out.write("\t\tvar brwfrm = document.brwform;\n");
      out.write("\t\tbrwfrm.action = \"borrow.bill\";\n");
      out.write("\t\tbrwfrm.target = \"BORROW\";\n");
      out.write("\t\tbrwfrm.submit();\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction cmtAdd() {\n");
      out.write("\t\tvar gsWin = window.open(\"about:blank\", \"COMMENT\",  'width=500, height=500');\n");
      out.write("\t\tvar cmtfrm = document.cmtform;\n");
      out.write("\t\tcmtfrm.action = \"commentAdd.bill\";\n");
      out.write("\t\tcmtfrm.target = \"COMMENT\";\n");
      out.write("\t\tcmtfrm.submit();\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("\tbody{\t\t\t\n");
      out.write("\t\tmargin-left:100px;\n");
      out.write("\t\tmargin-right:100px;\n");
      out.write("\t\tmax-width:1000px;\n");
      out.write("\t\tpadding: auto;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\tul {\n");
      out.write("\t\tbackground-color: white;\n");
      out.write("\t\tlist-style-type: none;\n");
      out.write("\t\tmargin: 0;\n");
      out.write("\t\tpadding: 0;\n");
      out.write("\t\toverflow: hidden;\n");
      out.write("\t}\n");
      out.write("\tli { float: left; }\n");
      out.write("\tli a {\n");
      out.write("\t\tdisplay: block;\n");
      out.write("\t\tbackground-color: white;\n");
      out.write("\t\tcolor: #000000;\n");
      out.write("\t\tpadding: 8px;\n");
      out.write("\t\ttext-decoration: none;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tfont-weight: bold;\n");
      out.write("\t}\n");
      out.write("\tli a:hover:not(.current) {\n");
      out.write("\t\tbackground-color: silver;\n");
      out.write("\t\tcolor: purple;\n");
      out.write("\t\ttext-decoration:underline;\n");
      out.write("\t}\n");
      out.write("\tli a.home{\n");
      out.write("\t\tbackground-color: black;\n");
      out.write("\t\tcolor: white;\n");
      out.write("\t}\n");
      out.write("\tdiv.search{\t\t\n");
      out.write("\t}\n");
      out.write("\tdiv.logo{\n");
      out.write("\t}\n");
      out.write("\tdiv.posts{\n");
      out.write("\t}\n");
      out.write("\tdiv.posts-items{\n");
      out.write("\t}\n");
      out.write("\tdiv.posts-items-title{\n");
      out.write("\t}\n");
      out.write("\t.searchbox {\n");
      out.write("\t\twidth: 40%;\n");
      out.write("\t\tpadding: 10px 20px; \n");
      out.write("\t\tmargin:5px 0;\t\t\t\n");
      out.write("\t\tborder: solid 2px black;\n");
      out.write("\t\tborder-radius: 8px; \n");
      out.write("\t}\n");
      out.write("\tdiv.banner {position: relative; width: 100%; height: 210px; top: 50px;  margin:0 auto; padding:0; overflow: hidden;}\n");
      out.write("\tdiv.banner ul {position: absolute; margin: 0px; padding:0; list-style: none; }\n");
      out.write("\tdiv.banner ul li {float: left; width: 1000px; height: 210px; margin:0; padding:0;}\n");
      out.write("\t\n");
      out.write("\t.search {\n");
      out.write("\t  text-align: center;\n");
      out.write("\t}\n");
      out.write("\t.dropbtn {\n");
      out.write("\t  font-size: 16px;\n");
      out.write("\t  cursor: pointer;\n");
      out.write("\t}\n");
      out.write("\t \n");
      out.write("\t.dropdown {\n");
      out.write("\t  position: relative;\n");
      out.write("\t}\n");
      out.write("\t \n");
      out.write("\t.dropdown-content {\n");
      out.write("\t  display: none;\n");
      out.write("\t  position: relative;\n");
      out.write("\t  top: -70px;\n");
      out.write("      left: 500px;\n");
      out.write("      width: 120px;\n");
      out.write("\t  overflow: auto;\n");
      out.write("\t  box-shadow: 0px 8px 8px 0px rgba(0,0,0,0.2);\n");
      out.write("\t  background-color: white;\n");
      out.write("\t}\n");
      out.write("\t \n");
      out.write("\t.dropdown-content a {\n");
      out.write("\t  color: black;\n");
      out.write("\t  text-decoration: none;\n");
      out.write("\t  font-family : sans-serif;\n");
      out.write("\t  display: block;\n");
      out.write("\t}\n");
      out.write("\t \n");
      out.write("\t.dropdown a:hover {background-color: #ddd;}\n");
      out.write("\t \n");
      out.write("\t.show {display: block;}\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("<style> /* produt Detail style */\n");
      out.write("\n");
      out.write("\t.prdDetail {\n");
      out.write("\t\tborder: solid 2px black;\n");
      out.write("\t\tborder-radius: 8px;\n");
      out.write("\t\tmargin-top: 20px;\n");
      out.write("\t\tposition: 50%;\n");
      out.write("\t\tfont-family: sans-serif;\n");
      out.write("\t\twidth:860px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.title {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.prImage { grid-area: prImg; height: 400px; width: 400px; background-color: rgba(231, 235, 238, 100); margin-left: 50px;}\n");
      out.write("\t.infoText { grid-area: ifText; height: 230px; }\n");
      out.write("\t.borrow { grid-area: borrow; }\n");
      out.write("\t \n");
      out.write("\t.detailInfo {\n");
      out.write("\t  display: grid;\n");
      out.write("\t  grid-template-areas:\n");
      out.write("\t    'prImg ifText'\n");
      out.write("\t    'prImg borrow';\n");
      out.write("\t  grid-gap: 5px;\n");
      out.write("\t  font-family: sans-serif;\n");
      out.write("\t  text-align: center;\n");
      out.write("\t  margin-top : 20px;\n");
      out.write("\t  margin-bottom : 20px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.infoText {\n");
      out.write("\t\tmargin-top: 20px;\n");
      out.write("\t\tmargin-right: 50px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.borrow {\n");
      out.write("\t\tborder: solid 1px silver;\n");
      out.write("\t\tborder-radius: 8px; \n");
      out.write("\t\tmargin-right: 50px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t.details {\n");
      out.write("\t  margin-left: 50px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.startDate { grid-area: sd; }\n");
      out.write("\t.endDate { grid-area: ed; }\n");
      out.write("\t.sdatekeyin { grid-area: sdkey; }\n");
      out.write("\t.edatekeyin { grid-area: edkey; }\n");
      out.write("\n");
      out.write("\n");
      out.write(" \t.brwHead {\n");
      out.write("\t\tdisplay : flex;\n");
      out.write("\t\tflex-direction: row;\n");
      out.write("\t\tmargin-top:10px;\n");
      out.write("\t\twidth : 94%;\n");
      out.write("\t\tpedding: 20px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.price {\n");
      out.write("\t\tflex: 1;\n");
      out.write("\t\tmargin-top:5px;\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.etcInfo {\n");
      out.write("\t\tflex: 1;\n");
      out.write("\t\n");
      out.write("\t}\n");
      out.write(" \t.date {\n");
      out.write(" \t\tdisplay: grid;\n");
      out.write("\t  \tgrid-template-areas:\n");
      out.write("\t    'sd ed'\n");
      out.write("\t    'sdkey edkey';\n");
      out.write("\t\tborder: solid 1px silver;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tmargin: 10px 2px 10px 2px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.startDate {\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tborder-right: solid 1px silver;\n");
      out.write("\t\tfont-weight: bold;\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.endDate {\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tfont-weight: bold;\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.sdatekeyin {\n");
      out.write("\t\tfont-size: 15px;\n");
      out.write("\t\tborder-right: solid 1px silver;\n");
      out.write("\t}\n");
      out.write("\t.edatekeyin {\n");
      out.write("\t\tfont-size: 15px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.brwBtn {\n");
      out.write("\t\tmargin-top: 15px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<style> /* comment style  */\n");
      out.write("\n");
      out.write("\t.comment {\n");
      out.write("\t\tmargin-top:10px;\n");
      out.write("\t\tborder: solid 2px black;\n");
      out.write("\t\tborder-radius: 8px;\n");
      out.write("\t\tfont-family: sans-serif;\n");
      out.write("\t\twidth:860px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.commentTable {\n");
      out.write("\t\tdisplay : flex;\n");
      out.write("\t\tflex-direction: row;\n");
      out.write("\t\tmargin : 5px;\n");
      out.write("\t\tmargin-left: 20px;\n");
      out.write("\t\twidth : 90%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.cmtNick {\n");
      out.write("\t\tflex: 1;\n");
      out.write("\t\tfont-weight: bold;\n");
      out.write("\t\tflex-basis: 15%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.cmtText {\n");
      out.write("\t\tflex: 1;\n");
      out.write("\t\tflex-basis: 50%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.cmtDate {\n");
      out.write("\t\tflex: 1;\n");
      out.write("\t\tflex-basis: 20%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.cmtRev {\n");
      out.write("\t\tflex: 1;\n");
      out.write("\t\tflex-basis: 5%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.cmtBtn {\n");
      out.write("\t\tfont-size: 8;\n");
      out.write("\t\tborder:0;\n");
      out.write("\t\tbackground-color: white;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.cmtDel {\n");
      out.write("\t\tflex: 1;\n");
      out.write("\t\tflex-basis: 5%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.cmtTxt {\n");
      out.write("\t\tborder-radius: 8px;\n");
      out.write("\t\tborder-top: solid 1px silver;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t\twidth:85%;\n");
      out.write("\t\theight:30px;\n");
      out.write("\t\toverflow:visible;\n");
      out.write("\t\ttext-overflow:ellipsis;\n");
      out.write("\t\tmargin-left : 20px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<style> /* 목록 수정 삭제 style */\n");
      out.write("\t\n");
      out.write("\t.prdFooter {\n");
      out.write("\t\tdisplay : flex;\n");
      out.write("\t\tflex-direction: row;\n");
      out.write("\t\tjustify-content: flex-end;\n");
      out.write("\t\tmargin-top:10px;\n");
      out.write("\t\tpedding: 20px;\n");
      out.write("\t\tfont-size: 20px;\n");
      out.write("\t\tfont-family: sans-serif;\n");
      out.write("\t\twidth:860px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.list {\n");
      out.write("\t\tflex: 0 1;\n");
      out.write("\t\tflex-basis: 20px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.prdRev {\n");
      out.write("\t\tflex: 0 1;\n");
      out.write("\t\tflex-basis: 20px;\n");
      out.write("\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.prdDel {\n");
      out.write("\t\tflex: 0 1;\n");
      out.write("\t\tflex-basis: 20px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>빌릴꼬냥? 상품 세부정보당</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<form action=\"search.bill\"> \n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t\t<li><a class=\"home\" href=\"refresh.bill\">홈</a></li>\n");
      out.write("\t\t\t<ul style=\"float:right; list-style-type:none;\">\n");
      out.write("\t\t\t\t<li><a href=\"logout.bill\">로그아웃</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"mypage.bill\">마이페이지</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<h1 style= \"text-align: center;\">빌릴꼬냥</h1>\n");
      out.write("\t\t<div class=\"search\">\n");
      out.write("\t\t\t<input type=\"text\" class=\"searchbox\" placeholder =\"상품명, 제품명, 지역명 입력\" name=\"search\">\n");
      out.write("\t\t\t<input type=\"submit\" value=\"검색\" style=\"width: 50px; height:40px; border-radius: 8px; color: white; background-color: black;\"> \n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t<div class=\"prdDetail\">\n");
      out.write("\t\t<div class=\"title\">\n");
      out.write("\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\n");
      out.write("\t\t\t\t<div class=\"dropdown\">\n");
      out.write("\t\t\t\t  <button onclick=\"myFunction()\" class=\"dropbtn\" style=\"width: 100px; height:30px; border-radius: 8px; background-color: rgba(231, 235, 238, 100);\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\n");
      out.write("\t\t\t\t  <h5>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.xaxis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.yaxis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </h5> \n");
      out.write("\t\t\t\t  <div id=\"myDropdown\" class=\"dropdown-content\">\n");
      out.write("\t\t\t\t    <a href=\"userinfoDetail.bill?nickname=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"window.open(this.href,'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("의 정보','width=200, height=200'); return false;\">사용자 정보</a>\n");
      out.write("\t\t\t\t    <a href=\"messageSend.bill?nickname=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"window.open(this.href,'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("에게 쪽지 보내기','width=850, height=600'); return false;\">쪽지 보내기</a>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"details\">\n");
      out.write("\t\t\t<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.hash }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("\t\t\t<h5>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.date1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.date2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"detailInfo\">\n");
      out.write("\t\t\t<div class=\"prImage\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.image1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t<div class=\"infoText\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t<div class=\"borrow\">\n");
      out.write("\t\t\t\t<div class=\"brwHead\">\n");
      out.write("\t\t\t\t\t<div class=\"price\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 원 / 일</div>\n");
      out.write("\t\t\t\t\t<div class=\"etcInfo\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${like}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.view }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<form name=\"brwform\" action=\"\" method=\"post\">\n");
      out.write("\t\t\t\t<div class=\"date\">\n");
      out.write("\t\t\t\t\t<div class=\"startDate\">시작</div>\n");
      out.write("\t\t\t\t\t<div class=\"sdatekeyin\"><input type=\"text\" name=\"syy\" placeholder=\"yy\" size=\"3\">년\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"smm\" placeholder=\"mm\" size=\"3\">월\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sdd\" placeholder=\"dd\" size=\"3\">일\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"endDate\">끝</div>\n");
      out.write("\t\t\t\t\t<div class=\"edatekeyin\"><input type=\"text\" name=\"eyy\" placeholder=\"yy\" size=\"3\">년\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"emm\" placeholder=\"mm\" size=\"3\">월\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"edd\" placeholder=\"dd\" size=\"3\">일\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<INPUT type=\"hidden\" name=\"brprdseq\" value=\"");
      out.print(request.getParameter("prdseq"));
      out.write("\">\n");
      out.write("\t\t\t\t\t<INPUT type=\"hidden\" name=\"brmynick\" value=\"수키\">\n");
      out.write("\t\t\t\t<div class=\"brwBtn\">\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"빌리기\" onclick=\"borrowAct();\" style=\"width: 100px; height:30px; border:solid 1px silver; border-radius: 8px; background-color: white;\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div> \n");
      out.write("\t\n");
      out.write("\t<div class=\"comment\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"commentList\">\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"commentAdd\">\n");
      out.write("\t\t\t\t<form name=\"cmtform\" action=\"\" method=\"post\" >\n");
      out.write("\t\t\t\t\t<INPUT type=\"hidden\" name=\"prdseq\" value=\"");
      out.print(request.getParameter("prdseq"));
      out.write("\">\n");
      out.write("\t\t\t\t\t<INPUT type=\"hidden\" name=\"myseq\" value=10> <!-- !!!!!!!!!!!!!!!!!!10 대신에 나의 userseq !!!!!!!!!! -->\n");
      out.write("\t\t\t\t\t<div class=\"cmtAdd\" style=\"margin-top:10px; margin-bottom:10px;\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"cmtTxt\" name=\"cmtTxt\" style=\"border-radius: 8px; border-top: solid 1px silver; vertical-align: middle;\">\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"등록\" onclick=\"cmtAdd();\" style=\"width: 60px; height:30px; border:solid 1px silver; border-radius: 8px; margin-left:20px; background-color: white;\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"prdFooter\">\n");
      out.write("\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /productDetail.jsp(441,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdDetail.nickname eq '쯩'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t<div class=\"list\">\n");
            out.write("\t\t\t\t<input type=\"button\" value=\"목록\" onclick=\"location.href='home.bill'\" >\n");
            out.write("\t\t\t</div>\n");
            out.write("\t\t\t<div class=\"prdRev\">\n");
            out.write("\t\t\t\t<input type=\"button\" value=\"수정\" onclick=\"location.href='prdCheck.bill?prdseq=");
            out.print(request.getParameter("prdseq"));
            out.write("'\" >\n");
            out.write("\t\t\t</div>\n");
            out.write("\t\t\t<div class=\"prdDel\">\n");
            out.write("\t\t\t\t<input type=\"button\" value=\"삭제\" onclick=\"window.open('prdDel.bill?prdseq=");
            out.print(request.getParameter("prdseq"));
            out.write("','게시물 삭제','width=500,height=500');\" >\n");
            out.write("\t\t\t</div>\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /productDetail.jsp(414,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/productDetail.jsp(414,4) '${cmtDetail }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cmtDetail }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /productDetail.jsp(414,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cmt");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t<div class=\"commentTable\">\n");
            out.write("\t\t\t\t\t\t<div class=\"cmtNick\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmt.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </div>\n");
            out.write("\t\t\t\t\t\t<div class=\"cmtText\" style=\"word-break:break-all\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmt.comment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </div>\n");
            out.write("\t\t\t\t\t\t<div class=\"cmtDate\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmt.insertdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </div>\n");
            out.write("\t\t\t\t\t\t<div class=\"cmtRev\" >\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t<!-- !!!!!!!!!!!!!!!!!!10 대신에 나의 userseq 받아오게!!!!!!!!!! -->\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /productDetail.jsp(420,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmt.userCheck eq 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"button\" class=\"cmtBtn\" value=\"수정/삭제\" onclick=\"window.open('commentCheck.bill?cmtseq=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmt.cmtseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("','팝업이름','width=500,height=500');\" >");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
